CREATE TABLE Student (
    StudentID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    PasswordSalt VARCHAR(255) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    Surname VARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    DateCreated TIMESTAMP,
    LastLogin TIMESTAMP,
    FailedAttempts INT DEFAULT 0,
    BlockedUntil TIMESTAMP,
    AccountActive BOOLEAN DEFAULT 'True'
);

CREATE TABLE Subject(
    StudentID BIGINT REFERENCES Student(StudentID),
	SubjectID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	SubjectName VARCHAR(30)NOT NULL,
	ExamBoard VARCHAR(15)NOT NULL,
	CourseLevel VARCHAR(10)NOT NULL
);


CREATE TABLE Homework(
    StudentID BIGINT REFERENCES Student(StudentID),
	SubjectID BIGINT REFERENCES Subject(SubjectID),
	HomeworkID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Title VARCHAR(225)NOT NULL,
	Description VARCHAR(500)NOT NULL,
	DueDate DATE NOT NULL,
	Completed BOOLEAN DEFAULT 'False',
	DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HomeworkTask(
    HomeworkID BIGINT REFERENCES Homework(HomeworkID),
	HomeworkTaskID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	TaskName VARCHAR(225)NOT NULL,
	Completed BOOLEAN DEFAULT 'False',
	Description VARCHAR(500),
	DateCompleted DATE NOT NULL
);

CREATE TABLE ToDoList(
    StudentID BIGINT REFERENCES Student(StudentID),
	ToDoID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	TaskName VARCHAR(225)NOT NULL,
	DueDate DATE NOT NULL,
	Priority VARCHAR(5)NOT NULL,
	Completed BOOLEAN DEFAULT 'False',
	DateCreated TIMESTAMP NOT NULL,
	Description VARCHAR(500)NOT NULL
);

CREATE TABLE Resource(
    SubjectID BIGINT REFERENCES Subject(SubjectID),
	ResourceID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ResourceTitle VARCHAR(150)NOT NULL,
	ResourceType VARCHAR(50)NOT NULL,
	ResourceLocation VARCHAR(500)NOT NULL,
	ExamBoard VARCHAR(15)NOT NULL,
	DateAdded DATE NOT NULL
);

CREATE TABLE StudentNotes(
    StudentID BIGINT REFERENCES Student(StudentID),
	SubjectID BIGINT REFERENCES Subject(SubjectID),
	NoteID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NoteTitle VARCHAR(150)NOT NULL,
	NoteContent Text NOT NULL,
	ImageLocation VARCHAR(500)NOT NULL,
	TypeOfNote VARCHAR(100)NOT NULL,
	DateCreated DATE NOT NULL,
	DateUpdated TIMESTAMP NOT NULL
);

CREATE TABLE Grades(
    StudentID BIGINT REFERENCES Student(StudentID),
	SubjectID BIGINT REFERENCES Subject(SubjectID),
	GradeID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	AssesmentName VARCHAR(150)NOT NULL,
	Score DECIMAL(5,2)NOT NULL,
	MaxScore DECIMAL(5,2)NOT NULL,
	Percentage DECIMAL(5,2)NOT NULL,
	GradeValue VARCHAR(10)NOT NULL,
	AssessmentDate DATE NOT NULL
);

CREATE TABLE RevisionAttempt(
    StudentID BIGINT REFERENCES Student(StudentID),
	SubjectID BIGINT REFERENCES Subject(SubjectID),
	RevisionAttemptID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Topic VARCHAR(150)NOT NULL,
	Score INT NOT NULL,
	TotalQuestions INT NOT NULL,
	TimeSpentMin INT NOT NULL,
	AttemptDate DATE NOT NULL
);

CREATE TABLE Progress(
    StudentID BIGINT REFERENCES Student(StudentID),
	SubjectID BIGINT REFERENCES Subject(SubjectID),
	ProgressID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Topic VARCHAR(150)NOT NULL,
	AverageScore DECIMAL(5,2)NOT NULL,
	CompletionPercentage DECIMAL(5,2)NOT NULL,
	StrengthStatus VARCHAR(50)NOT NULL,
	DateUpdated TIMESTAMP NOT NULL
);	

CREATE TABLE Alert(
    StudentID BIGINT REFERENCES Student(StudentID),
    AlertID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	AlertTitle VARCHAR(100)NOT NULL,
	AlertMessage VARCHAR(500)NOT NULL,
	AlertDate TIMESTAMP NOT NULL,
	ReadStatus BOOLEAN DEFAULT 'False',
	AlertType VARCHAR(30)NOT NULL
);	

CREATE TABLE AIQuestion(
    StudentID BIGINT REFERENCES Student(StudentID),
	SubjectID BIGINT REFERENCES Subject(SubjectID),
	QuestionID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Topic VARCHAR(150)NOT NULL,
	Difficulty VARCHAR(30)NOT NULL,
	QuestionText Text NOT NULL,
	DateGenerated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AIAnswers(
    QuestionID BIGINT REFERENCES AIQuestion(QuestionID),
    AnswerID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	AnswerText Text NOT NULL,
	WorkingOut Text NOT NULL,
	DateGenerated TIMESTAMP NOT NULL
);